RAM:
  UBX-CFG-VALSET:
    # enable survey-in mode
    - CFG-TMODE-MODE: 1
    - CFG-TMODE-SVIN_MIN_DUR: 60
    - CFG-TMODE-SVIN_ACC_LIMIT: 100000

    # disable all output except RTCM on uart1
    - CFG-UART1OUTPROT-UBX: 0
    - CFG-UART1OUTPROT-NMEA: 0
    - CFG-UART1OUTPROT-RTCM3X: 1

    # enable rtcm messages
    - CFG-MSGOUT-RTCM_3X_TYPE1005_UART1: 1
    - CFG-MSGOUT-RTCM_3X_TYPE1074_UART1: 1
    - CFG-MSGOUT-RTCM_3X_TYPE1084_UART1: 1
    - CFG-MSGOUT-RTCM_3X_TYPE1124_UART1: 1
    - CFG-MSGOUT-RTCM_3X_TYPE1230_UART1: 5

    # change baudrate
    - CFG-UART1-BAUDRATE: 460800

Flash:
  UBX-CFG-VALSET:
    # change baudrate
    - CFG-UART1-BAUDRATE: 460800
